version: "3.4"

services:
  server:
    container_name: aplication
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run start
