import Head from "next/head";
import { Inter } from "@next/font/google";
import useData from "../hooks/useData";
import "../styles/Home.module.css";
import { TableData } from "../components/Table";
import { useEffect, useState } from "react";
import getType from "./api/type";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //USING CUSTOM HOOK
  const { dataAPI, setDataAPI } = useData();

  const [filterIndicator, setFilterIndicator] = useState("");

  if (!dataAPI) {
    return <div className="loader">Loading...</div>;
  }

  const handleChange = (e) => {
    setFilterIndicator(e.target.value);
  };

  // const convertData = data => {
  // 	return data;
  // };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const newData = await getType(filterIndicator);
    console.log("file: index.js:32  handleSubmit  newData", newData);
    // const convertedData = convertData(newData);
    setDataAPI(newData);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-container">
        <h1>INDICADORES ECONÓMICOS</h1>
        <form className="input-container" onSubmit={handleSubmit}>
          <label htmlFor="name-indicator">
            Ingrese el indicador:
            <input
              type="text"
              id="name-indicator"
              value={filterIndicator}
              onChange={handleChange}
            />
            <button type="submit">Buscar</button>
          </label>
          <label htmlFor="date-indicator">
            Busqueda por fecha:
            <input type="date" id="date-indicator" />
          </label>
        </form>
        <TableData data={dataAPI} />
      </main>
    </>
  );
}
